### ISSUE TITLE
Can you add 7x7 support?

### ISSUE THREAD

**Issue by St0RM53** [scottrini/OctoPrint-PrusaLevelingGuide#14]
It seems to only measure 3x3 grid :/ 

I know those are the screws for adjustment but the extra points can show more variation in the bed which is useful.

Kind regards

**Comment by scottrini** [comment]
Hey, sorry I missed responding, but it can easily be used for 7x7.  If you go into settings and edit the mesh leveling gcode, remove the N3 from the G80.  By default, it's `G80 N3` to force 3x3 even if 7x7 is set in your firmware.  If you just delete the `N3`, it'll run whatever you have configured in your firmware.

The plugin will never show more than the current grid, but you can make this change in the settings to have it measure all 49 points.

**Comment by St0RM53** [comment]
Thanks for the reply. However you should change it so it show the variation measured when 7x7 even though you can't adjust it.

**Comment by scottrini** [comment]
It **will** show the measured variations when doing 7x7, but it'll just only be in the grid that matches the screws.  The plugin is specifically for the nylock method and the values for spots you can't adjust are irrelevant to leveling with the nylock mod.  You'll still get more accurate measurements if you switch it to 7x7.

**Comment by St0RM53** [comment]
Ok thank you very much
