### ISSUE TITLE
Feature Request: Increase Precision

### ISSUE THREAD

**Issue by GrubbyZebra** [scottrini/OctoPrint-PrusaLevelingGuide#18]
Would it possible to increase the precision of the raw values display to 3 decimal places, instead of 2?

**Comment by scottrini** [comment]
I could, I could even remove rounding altogether, but it doesn't add any benefit.  I'd bet a lot of money that if I handed someone two screws or potentiometers and told them to turn one by 1.256 turns vs 1.257 turns, no one would be able to differentiate between the two.  So it really isn't helpful and then you need the additional space in the UI.

So it's perfectly doable, but I don't like this at all.
If you'd like to fork and take a stab at it and submit a PR, I'd review it.
Here's where it's rounding: https://github.com/scottrini/OctoPrint-PrusaLevelingGuide/blob/master/octoprint_PrusaLevelingGuide/__init__.py#L106
The backend rounds the values then passes them off to the frontend.  If we wanted to go all out, we'd remove rounding from the backend altogether and add an option to the frontend to adjust precision, so everyone is happy.

**Comment by GrubbyZebra** [comment]
the reason for the precision in the raw measures is for those using shims and custom length spacers, not for turning screws.

**Comment by scottrini** [comment]
The intention of this plugin is specifically the nylock method, so turning screws. Like I said, I don't like that for this plugin. Feel free to create your own fork. If it's configurable, you can submit a PR and I might be willing to merge it in.

**Comment by scottrini** [comment]
Actually, I think I might push an update so the raw values aren't rounded at all.
