### ISSUE TITLE
Additional profiles

### ISSUE THREAD

**Issue by Ramwells** [scottrini/OctoPrint-PrusaLevelingGuide#19]
Please could you advise how to add additional Profiles - I would like to have one which is for PETG with a bed temperature of 85-90 deg C. 

Many thanks

**Comment by scottrini** [comment]
Sure, they're just the profiles that are in your octoprint instance.

So go into Octoprint's settings, then in the left column click Temperatures.  At the bottom, you can click the + button and add a profile.

**Comment by Ramwells** [comment]
Brilliant, thanks Scott -- I missed the documentation about that !!!

**Comment by scottrini** [comment]
No problem!
