### ISSUE TITLE
Can the head be parked a bit to the right?

### ISSUE THREAD

**Issue by yoyo42** [scottrini/OctoPrint-PrusaLevelingGuide#22]
It is very hard to reach the back left adjustment screw because the extruder is moved to that corner between cycles. If the head was parked between the back left and back centre screws it would be a lot easier to reach..

**Comment by scottrini** [comment]
This is configurable in the settings. Just change the movement gcode to your liking.

**Comment by yoyo42** [comment]
Thanks, adding an X65 to to the move gcode and lifting it 20mm higher makes it much easier to adjust.
