### ISSUE TITLE
Degree value not updating

### ISSUE THREAD

**Issue by englolo** [scottrini/OctoPrint-PrusaLevelingGuide#23]
https://github.com/scottrini/OctoPrint-PrusaLevelingGuide/blob/ca3a5395d2f995ccba8fc5947e46e1c70900213e/octoprint_PrusaLevelingGuide/static/js/PrusaLevelingGuide.js#L217

I manually changed back to previous and is working
        `newBedValues.push(Math.abs(value)  + '°');`

**Comment by scottrini** [comment]
That's weird - I had it working locally before pushing the change.  Thanks for the info, I'll get it fixed and updated today.

**Comment by scottrini** [comment]
Fixed in [1.0.11](https://github.com/scottrini/OctoPrint-PrusaLevelingGuide/releases/tag/1.0.11)
