### ISSUE TITLE
Bug: Overlay not in correct position on bed

### ISSUE THREAD

**Issue by limited660** [scottrini/OctoPrint-PrusaLevelingGuide#25]
The boxes don't position correctly over the bed image.

![image](https://user-images.githubusercontent.com/4389136/97116497-eae94a00-16d3-11eb-8a5c-06bbec84a095.png)

**Comment by scottrini** [comment]
This isn't a bug, this is from your custom css from your theme. The plugin works with themeify's discorded theme and the default, but that's about it.

**Comment by limited660** [comment]
This is the discorded theme...

**Comment by limited660** [comment]
Also not aligned with Themeify turned off.

**Comment by scottrini** [comment]
Then you either have another plugin installed that changes the css (like the one that expands the view for wide screen monitors) or you have some custom css defined.  The only thing that can throw these off is custom css.  On a base octoprint install without any modifications, it'll line up as expected.  You can simply just switch to the table view.
