### ISSUE TITLE
When using the plugin the entry "control:" in config.yaml is deleted 

### ISSUE THREAD

**Issue by Nedial** [scottrini/OctoPrint-PrusaLevelingGuide#28]
OctoPrint 1.5.3
After each use of the plugin, the custom controls are deleted. The whole section is deleted in config.yaml.

**Comment by scottrini** [comment]
You mean the "controls" section, right?  I have custom controls defined in my config.yaml and I've used the plugin many times and it's never cleared this.  The plugin does initiate a save all settings, so the only way for settings to be lost is if they aren't already in the settings object.

I can't reproduce the problem, so this is probably not something I'd work on, but a PR is welcome if you think you can locate it.
