### ISSUE TITLE
align buttons / picture centered to window

### ISSUE THREAD

**Issue by ruedli** [scottrini/OctoPrint-PrusaLevelingGuide#3]
On my slightly wider screen, it becomes apparent that the horizontal alignment is different for three elements:

Picture is centered.
Two top rows of screws indicators are left aligned.
Bottom row of screw indicator is right aligned.

See picture...

Best way is to have everything centered aligned.

![image](https://user-images.githubusercontent.com/5008440/71132041-ba549c00-21f6-11ea-8598-b572d73fb09d.png)

**Comment by scottrini** [comment]
This isn't a matter of simply center aligning. It's made for a fixed width and uses relative positioning to position each field over the image. Unfortunately, this will not be modified. Feel free to submit a pull request if you want to structure it differently without breaking anything.
