### ISSUE TITLE
req: manual profiles for different filaments / heating bed

### ISSUE THREAD

**Issue by islander2013** [scottrini/OctoPrint-PrusaLevelingGuide#33]
could you add some more options to the preheat profile, such as ASA, PC, etc please. Also, to add custom profiles? thanks!

**Comment by scottrini** [comment]
The plugin uses the profiles that are defined in octoprint.  They're not hardcoded in the plugin.  So you can just add those other profiles to your octoprint instance.

**Comment by islander2013** [comment]
thank you so much! i didnt know this, perfect!!!
