### ISSUE TITLE
Prusa Bear AIO Marlin BTT002 uses g29 not g80 and i need to use this plugin please help

### ISSUE THREAD

**Issue by KI5QMT** [scottrini/OctoPrint-PrusaLevelingGuide#52]
I have a Prusa bear mk3s that uses a bigtreetech BTT002 board with Prusa AIO Bear firmware based off of marlin 2.1.X and I need to use this plugin to level bed using nylock nuts since marlin removes the prusa bed mesh adjust feature, heres a link to the firmware https://github.com/thisiskeithb/PrusaAIO

**Comment by scottrini** [comment]
You can change g28 to g80 in the settings.  That has always been exposed.  If the output does not match the normal output, it's not going to match and find the values.  This plugin is not intended to be used with other firmware aside from the official, so this will never be supported by the plugin directly if additional work is required.
