### ISSUE TITLE
Preheat time?

### ISSUE THREAD

**Issue by jurassic73** [scottrini/OctoPrint-PrusaLevelingGuide#53]
Once my bed leveling was tuned at 0.02 variance, I let my printer cool down and came back later(a few hours) to run the leveling again and the first pass showed variance at 0.1. I didn't make any adjustments and then ran the leveling two more times by clicking continue and it came back with 0.32 variance. I'm guessing it takes time to heat up the metal bed carrier along with the bed/sheet. The whole area needs to heat up adequately to get back to where it's tuned to. If I don't let it heat up, it says I have a lot of changes to make.

I'm pondering adding a one minute delay to my prints in the slicer so things heat up to get a more accurate leveling.

I'm curious if you could add an option to your leveling plug-in to allow a user to let things heat up and then idle for say two minutes so that heated bed heat can work it's way down into the carrier metal as well?

**Comment by jurassic73** [comment]
Also - curious if history of readings has been considered? This is a great mod you've put together. Especially like the different ways you can read the variance.

**Comment by scottrini** [comment]
I understand the concern, but this can easily be done by preheating prior to using the plugin.  If you disable the preheat in the plugin and just have the printer preheated previously, you'll have that preheat time.  This isn't planned to be added.
