### ISSUE TITLE
Table view does not show correct direction of turn

### ISSUE THREAD

**Issue by hjschiller** [scottrini/OctoPrint-PrusaLevelingGuide#55]
When I view the results in the table form all points (except the center) show they need a clockwise turn, but when I view the results on the heat bed I can see some need a clockwise turn and some need a counter clockwise turn.
![IMG_7487](https://github.com/user-attachments/assets/006d64af-7d82-43ea-8587-bee5b41a95e7)
![IMG_7486](https://github.com/user-attachments/assets/21c9d5c1-5e54-4b51-81ee-c405067daf7f)

Is this the expected behavior?

**Comment by hjschiller** [comment]
The heat bed view has the right information

**Comment by scottrini** [comment]
Hey there - good catch, I checked the code and I'm not sure why the table view isn't updating.  Unfortunately, I already finished giving away all the old MK3S's and only have some MK4S's and XL's, so I can't even test it anymore.

When it doesn't update - is the table view the currently displayed view?  Or do you switch to table view afterwards?  Could you try keeping the table view active and see if it updates?

It should update on there regardless if it's in view or not, but looking through the code without being able to test it, that's the only straw I have right now.

**Comment by scottrini** [comment]
Actually, I think I might see the issue...

**Comment by scottrini** [comment]
If I provide a build to test here, would you help me test it? @hjschiller

**Comment by hjschiller** [comment]
Yes I can test for you.  

I was seeing the issue while using the just the table view.

**Comment by scottrini** [comment]
[OctoPrint-PrusaLevelingGuide-1.0.18.zip](https://github.com/user-attachments/files/17246899/OctoPrint-PrusaLevelingGuide-1.0.18.zip)
Yeah, if it's the issue I think it is, it won't matter when, it's just a class mismatch.  Try this one and let me know

**Comment by hjschiller** [comment]
Still seeing the issue.  The table is all clockwise.

<img width="561" alt="Screenshot 2024-10-03 at 1 18 52 PM" src="https://github.com/user-attachments/assets/0f746650-36a6-41e6-9a3b-89dd1938642e">
<img width="561" alt="Screenshot 2024-10-03 at 1 18 37 PM" src="https://github.com/user-attachments/assets/8613f163-3dc4-4f79-8bd6-2fc3ca47ee2e">

**Comment by scottrini** [comment]
Are you sure it's using the latest code?

Interesting, that's the only thing in the code that doesn't match up, so I don't think there's anything else I can do for you.  If you feel like working on it and posting a PR, I'll review it!

**Comment by hjschiller** [comment]
It says it is version 1.0.18 (I  don't know what I was running before.

<img width="646" alt="Screenshot 2024-10-03 at 1 51 16 PM" src="https://github.com/user-attachments/assets/2057271f-0dbe-469d-89cf-3e225e9d9f5b">
<img width="878" alt="Screenshot 2024-10-03 at 1 49 26 PM" src="https://github.com/user-attachments/assets/818ae9da-975d-4bbe-9466-b9f435892f08">
<img width="512" alt="Screenshot 2024-10-03 at 1 48 54 PM" src="https://github.com/user-attachments/assets/8cae3160-2418-4ded-8cf4-0b5ba8879280">

**Comment by scottrini** [comment]
Did you remove the previous version, install, and restart?  It has to restart to apply the new code.

**Comment by hjschiller** [comment]
I did not remove the previous version... 
I will remove the current version then try a clean install from the zip now

**Comment by hjschiller** [comment]
Removing the previous version and re-installing fixed it.

__Jason

<img width="561" alt="Screenshot 2024-10-03 at 2 06 24 PM" src="https://github.com/user-attachments/assets/a9723e6a-4032-4833-a6b0-44e483562bd4">
<img width="563" alt="Screenshot 2024-10-03 at 2 06 07 PM" src="https://github.com/user-attachments/assets/72e1ebaa-a942-46d9-8a6d-d43b68c23c53">

**Comment by scottrini** [comment]
Perfect!  Yeah, the version number would stay the same - it was a test build.  Now that I know it cleared it up, I'll bump and tag a new version with the fix.  So you'll get a notice about an update in a day or two, you can go ahead and update, but you technically already have it.

**Comment by hjschiller** [comment]
Sounds good.

Feel free to ping me on email if you need help with MK3 testing in the future.

You are welcome to close this issue, either now, or with the next release.

**Comment by scottrini** [comment]
Fixed in [1.0.19](https://github.com/scottrini/OctoPrint-PrusaLevelingGuide/releases/tag/1.0.19)
