### ISSUE TITLE
Upgrade to 1.0.19 installs 1.0.18

### ISSUE THREAD

**Issue by thomergil** [scottrini/OctoPrint-PrusaLevelingGuide#56]
I get a warning that I need to install 1.0.19. I press update. I see it download 1.0.19, but the last message says that version 1.0.18 is installed. After a restart, I, again, get a notice that I need to upgrade to 1.0.19.

**Comment by thomergil** [comment]
<img width="314" alt="Screenshot 2024-10-12 at 2 09 13 PM" src="https://github.com/user-attachments/assets/81ffc1ea-fc37-4fb6-a52e-3a451c489e12">

<img width="574" alt="Screenshot 2024-10-12 at 2 09 20 PM" src="https://github.com/user-attachments/assets/b280c7b3-3c46-4d27-a886-6745f71e3422">

<img width="573" alt="Screenshot 2024-10-12 at 2 12 01 PM" src="https://github.com/user-attachments/assets/5e787013-3f74-4190-b8ac-f1342d71fb95">


<img width="568" alt="Screenshot 2024-10-12 at 2 12 07 PM" src="https://github.com/user-attachments/assets/2f757213-2acc-49ef-82e1-24e319eabcd8">

**Comment by scottrini** [comment]
Fixed in 1.0.20
