### ISSUE TITLE
Last step

### ISSUE THREAD

**Issue by darthjuanan** [scottrini/OctoPrint-PrusaLevelingGuide#8]
Thank for your work.

I do your previous steps, but in the "Update the UI with the values", I dont know how to... How to update the UI with the values in the Octopi?

Thanks in advance!!

**Comment by scottrini** [comment]
"Update the UI with the values" is what the plugin does - it displays the variances on screen.  You then need to use those values to adjust the screws in the nylock mod.  Then you click continue after making those adjustments to re-measure.

This is what you need to do - 
"Once the UI is updated, the status will change to Waiting for continue. This is your opportunity to adjust the screws. The raw value view does not provide the direction to turn the screws. If it's a negative value, loosen the screw. If it's positive, tighten the screw."
